// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: dapplink/notifier.proto

package notifier

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// NotifierServicesClient is the client API for NotifierServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierServicesClient interface {
}

type notifierServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierServicesClient(cc grpc.ClientConnInterface) NotifierServicesClient {
	return &notifierServicesClient{cc}
}

// NotifierServicesServer is the server API for NotifierServices service.
// All implementations should embed UnimplementedNotifierServicesServer
// for forward compatibility
type NotifierServicesServer interface {
}

// UnimplementedNotifierServicesServer should be embedded to have forward compatible implementations.
type UnimplementedNotifierServicesServer struct {
}

// UnsafeNotifierServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServicesServer will
// result in compilation errors.
type UnsafeNotifierServicesServer interface {
	mustEmbedUnimplementedNotifierServicesServer()
}

func RegisterNotifierServicesServer(s grpc.ServiceRegistrar, srv NotifierServicesServer) {
	s.RegisterService(&NotifierServices_ServiceDesc, srv)
}

// NotifierServices_ServiceDesc is the grpc.ServiceDesc for NotifierServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifierServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapplink.NotifierServices",
	HandlerType: (*NotifierServicesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "dapplink/notifier.proto",
}
