// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: dapplink/riskcontroller.proto

package riskcontroller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_dapplink_riskcontroller_proto protoreflect.FileDescriptor

const file_dapplink_riskcontroller_proto_rawDesc = "" +
	"\n" +
	"\x1ddapplink/riskcontroller.proto\x12\bdapplink2\x18\n" +
	"\x16RiskControllerServicesB\x1cZ\x1a../protobuf/riskcontrollerb\x06proto3"

var file_dapplink_riskcontroller_proto_goTypes = []any{}
var file_dapplink_riskcontroller_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dapplink_riskcontroller_proto_init() }
func file_dapplink_riskcontroller_proto_init() {
	if File_dapplink_riskcontroller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dapplink_riskcontroller_proto_rawDesc), len(file_dapplink_riskcontroller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dapplink_riskcontroller_proto_goTypes,
		DependencyIndexes: file_dapplink_riskcontroller_proto_depIdxs,
	}.Build()
	File_dapplink_riskcontroller_proto = out.File
	file_dapplink_riskcontroller_proto_goTypes = nil
	file_dapplink_riskcontroller_proto_depIdxs = nil
}
