// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: dapplink/riskcontroller.proto

package riskcontroller

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// RiskControllerServicesClient is the client API for RiskControllerServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskControllerServicesClient interface {
}

type riskControllerServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskControllerServicesClient(cc grpc.ClientConnInterface) RiskControllerServicesClient {
	return &riskControllerServicesClient{cc}
}

// RiskControllerServicesServer is the server API for RiskControllerServices service.
// All implementations should embed UnimplementedRiskControllerServicesServer
// for forward compatibility
type RiskControllerServicesServer interface {
}

// UnimplementedRiskControllerServicesServer should be embedded to have forward compatible implementations.
type UnimplementedRiskControllerServicesServer struct {
}

// UnsafeRiskControllerServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskControllerServicesServer will
// result in compilation errors.
type UnsafeRiskControllerServicesServer interface {
	mustEmbedUnimplementedRiskControllerServicesServer()
}

func RegisterRiskControllerServicesServer(s grpc.ServiceRegistrar, srv RiskControllerServicesServer) {
	s.RegisterService(&RiskControllerServices_ServiceDesc, srv)
}

// RiskControllerServices_ServiceDesc is the grpc.ServiceDesc for RiskControllerServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskControllerServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapplink.RiskControllerServices",
	HandlerType: (*RiskControllerServicesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "dapplink/riskcontroller.proto",
}
